### ISSUE TITLE
Panic on server startup with RelativeDir is empty

### ISSUE THREAD

**Issue by sbose78** [otaviof/chart-streams#2]
```make run
go run -v -mod=vendor cmd/chartstreams/* serve
INFO[0000] Starting server with config: '&config.Config{RepoURL:"https://github.com/helm/charts.git", RelativeDir:"", CloneDepth:1, ListenAddr:":8080"}' 
panic: file does not exist

goroutine 1 [running]:
main.runServeCmd(0x2037420, 0x2064d10, 0x0, 0x0)
        /Users/sbose/chart-streams/cmd/chartstreams/serve.go:43 +0x2d0
github.com/spf13/cobra.(*Command).execute(0x2037420, 0x2064d10, 0x0, 0x0, 0x2037420, 0x2064d10)
        /Users/sbose/chart-streams/vendor/github.com/spf13/cobra/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x20371a0, 0x0, 0x0, 0x2037420)
        /Users/sbose/chart-streams/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/sbose/chart-streams/vendor/github.com/spf13/cobra/command.go:864
main.main()
        /Users/sbose/chart-streams/cmd/chartstreams/main.go:53 +0x2e
exit status 2
```

**Comment by otaviof** [comment]
Issue is solved. Please try again.
